# Version: 0.1.0
version: '3'
services:
  db:
    container_name: ${PROJECT_NAME}_db
    restart: 'no'
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    image: 'mariadb:latest'
    networks:
      - wordpress_network
  wp:
    container_name: ${PROJECT_NAME}_wp
    image: wordpress:latest
    restart: 'always'
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
    volumes:
      - wpcontent:/var/www/html/wp-content
      - ./theme:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./plugins/acf-custom-repeater:/var/www/html/wp-content/plugins/acf-custom-repeater
      - ./config/mu-plugins:/var/www/html/wp-content/mu-plugins
    networks:
      - wordpress_network
    depends_on:
      - db
  pma:
    container_name: ${PROJECT_NAME}_pma
    image: phpmyadmin/phpmyadmin
    restart: 'always'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      UPLOAD_LIMIT: 50M
    ports:
      - '8081:80'
    networks:
      - wordpress_network
    depends_on:
      - db
  mailpit:
    container_name: ${PROJECT_NAME}_mailpit
    image: 'axllent/mailpit:latest'
    restart: 'always'
    ports:
      - '8025:8025'
      - '1025:1025'
    networks:
      - wordpress_network

networks:
  wordpress_network:
    name: ${PROJECT_NAME}_network

volumes:
  mysqldata:
    name: ${PROJECT_NAME}_mysqldata
  wpcontent:
    name: ${PROJECT_NAME}_wpcontent
